FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
RUN apt-get update && \
    apt-get install -y ffmpeg software-properties-common
COPY --from=ghcr.io/astral-sh/uv:0.4.29 /uv /uvx /bin/
ADD . /app
WORKDIR /app
RUN uv sync --frozen
ENTRYPOINT uv run api.py